
[project]
name = "file-ext-sorter"
version = "0.1.0"
description = "A file sorter based on file extensions"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Oleksandr Romashko", email = "alex.rmshk@gmail.com" }
]
requires-python = ">=3.8, <3.15"
dependencies = [
  "aiofiles>=24.1.0,<25.0.0",
  "aioshutil>=1.5,<2.0",
  "colorama>=0.4.6,<0.5.0",
]

# Conditional dependency for older Python
[project.optional-dependencies]
legacy = ["tomli>=2.2.1; python_version<'3.11'"]
dev = ["types-colorama>=0.4.15.20240311"]

[project.urls]
Homepage = "https://github.com/oleksandr-romashko"

[tool.poetry]
packages = [{ include = "file_ext_sorter", from = "src" }]

[project.scripts]
file-ext-sorter = "file_ext_sorter.cli:main"

[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"
